version: 0.1.{build}
configuration: Release
assembly_info:
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
build:
  publish_nuget: true
  verbosity: minimal