version: 0.1.{build}
configuration: Release
assembly_info:
  patch: true
  assembly_version: $(appveyor_build_version)
  assembly_file_version: $(appveyor_build_version)
build:
  publish_nuget: true
  verbosity: minimal
before_package:
- cmd: $(appveyor_build_folder)\update-version.ps1 -file $(appveyor_build_folder)\src\Konves.Osis\Konves.Osis.nuspec -version $(appveyor_build_version)
